include:
  - mariadb/compose.yaml
services:
  app:
    build:
      context: laravel-app
    container_name: "app"
    depends_on:
      mariadb:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./laravel-app
          target: /app
          ignore:
            - vendor
        - action: rebuild
          path: ./composer.json
        - action: rebuild
          path: ./package.json
    environment:
      - "APP_NAME=${APP_NAME:-Laravel}"
      - "APP_ENV=${APP_ENV:-local}"
      - "APP_KEY=${APP_KEY:?}"
      - "APP_DEBUG=${APP_DEBUG:-true}"
      - "APP_TIMEZONE=${APP_TIMEZONE:-UTC}"
      - "APP_URL=${APP_URL:-http://localhost}"
      - "APP_LOCALE=${APP_LOCAL:-en}"
      - "APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE:-en}"
      - "APP_FAKER_LOCALE=${APP_FAKER_LOCAL:-en_US}"
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mariadb"
      - "DB_PORT=3306"
      - "DB_DATABASE=${MARIADB_DATABASE:-laravel}"
      - "DB_USERNAME=${MARIADB_USERNAME:-laravel}"
      - "DB_PASSWORD=${MARIADB_PASSWORD:?}"
    ports:
      - "${HTTP_PORT:-80}:8000"
    tty: true
    volumes:
      - "app-data:/app/storage"
volumes:
  app-data:
